apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: techverito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: deependrasingh7773/backend:latest
          ports:
            - containerPort: 8080
          command: ["sh", "-c", "go run main.go"]
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "tech_verito"
            - name: DB_PASSWORD
              value: "Root@1234"
            - name: DB_NAME
              value: "techteam"
            - name: ALLOWED_ORIGINS
              value: "*"
