apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: techverito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "tech_verito"
            - name: POSTGRES_PASSWORD
              value: "Root@1234"
            - name: POSTGRES_DB
              value: "techteam"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-data
          emptyDir: {}
