apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: techverito
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi  # Adjust the storage size as needed
  storageClassName: default-storageclass  # Name of the StorageClass to use
