apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default-storageclass
provisioner: kubernetes.io/aws-ebs # Change this to the appropriate provisioner for your cluster
parameters:
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
